### ISSUE TITLE
Linux unit testing

### ISSUE THREAD

**Issue by ARMmaster17** [NETponents/Gerbil#91]
MSTest doesn't work on Linux, need new way to make sure that software is still compatible on the Mono framework. Should probably switch over to NUnit or something like that. @vinman07a said he could give it a shot over the weekend. Anyone who wants to do it just remove the `help wanted` tag and assign the issue to yourself.

**Comment by vinman07a** [comment]
I will take this

**Comment by ARMmaster17** [comment]
Ok, Linux building is already up and works on the latest version of Mono. The main issue lies in the fact that we use MSTest for unit testing, which does not work on Linux. If you can find a way to script input into the program, that will work just fine. We want to keep the real tests running on the Windows-based AppVeyor since it's faster and provides more readable results.

**Comment by vinman07a** [comment]
I will port it to nunit, I'll also try packaging it for Unix, Makefile for bsd, pkgbuild for arch, etc. Did you encounter any other issues running this under Linux?

**Comment by ARMmaster17** [comment]
Take a look at the file `~/.travis.yml`. There is a special command to build the project because it doesn't like the MSTest project file. Otherwise, it works nicely.

**Comment by ARMmaster17** [comment]
All of the existing unit tests are in the `~/GerbilTest/UnitTest1.cs` code file. Ignore the part about the password cracker, that one has some issues.

**Comment by vinman07a** [comment]
I can do this later today, I only have my FreeBSD box with me so I will
test it there.

**Comment by vinman07a** [comment]
Do you have a docker image?

**Comment by ARMmaster17** [comment]
I'll add in a NUnit test solution on my own branch (ARMmaster17-91), then merge it back to the dev branch where you can work on it from there.

**Comment by ARMmaster17** [comment]
Running into issues, see #98.

**Comment by ARMmaster17** [comment]
Finally finished. Trace on PR #97.
